POST http://localhost:3000/advertisements
Content-Type: application/json

{
  "brandName": "Adidas",
  "logoPath": "/uploads/logo.png",
  "bannerPath": "/uploads/banner.png",
  "discountCode": "ADIDAS20"
}

###

GET http://localhost:3000/advertisements/game/3

###

POST http://localhost:3000/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="test_logo.png"
Content-Type: image/png

< ./uploads/test_logo.png
--WebAppBoundary--