POST http://localhost:3000/advertisements
Content-Type: application/json

{
  "brandName": "Adidas",
  "logoPath": "/uploads/1780593091546-test_logo.png",
  "bannerPath": "/uploads/test_banner.png",
  "discountCode": "ADIDAS20"
}

###

GET http://localhost:3000/advertisements/8/coupons

###
GET http://localhost:3000/advertisements/game/4
###

POST http://localhost:3000/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="test_logo.png"
Content-Type: image/png

< ./uploads/test_logo.png
--WebAppBoundary--

###
POST http://localhost:3000/coupons/generate
Content-Type: application/json

{
  "advertisementId": 7
}

###
GET http://localhost:3000/coupons/MJSKKP8V

###
POST http://localhost:3000/coupons/redeem/MJSKKP8V

###
GET http://localhost:3000/coupons